service: lambda-enviroment

# frameworkVersion: '2'
#
# useDotenv: true
# variablesResolutionMode: 20210326
# disabledDeprecations:
#   - CODE_1 # To disable specific deprecation with code "CODE_1"
#   - '*' # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "qa"}
  environment:
    ${file(./config/env.${self:provider.stage}.json)}
  iam.role.statements:
    ${file(./config/serverless/db.iam.role.yaml)}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
        rate: ${self:custom.schedulerRate}
        name: schedule-commit-message-${self:provider.stage}
        description: get commit messages each minute
        enabled: ${self:custom.enabled}

