org: wagnercastro
app: api-management
service: api-management

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
